version: 0.2

phases:
  build:
    commands:
      - cd ProductDisplay && mvn clean package -Dmaven.test.skip=true

artifacts:
discard-paths: yes
  artifacts:
  files:
    - appspec.yml
    - target/ProductDisplay.jar
    - scripts/*
